### ISSUE TITLE
插件中的callSmarthomeApi 其中有一个支持host （hostPrefix） 独立app 是否可以支持

### ISSUE THREAD

**Issue by hudson-s** [MiEcosystem/mijiaSDK#11]
/**
     * ApiLevel:58 调用智能家居后台http服务
     *
     * @param model       插件model
     * @param hostPrefix  HOST前缀
     * @param relativeUrl 服务接口url
     * @param method      请求方法
     * @param params
     * @param callback
     * @param parser
     */
    public abstract <T> void callSmartHomeApi(String model, String hostPrefix, String relativeUrl, String method, JSONObject params,
                                              final Callback<T> callback, final Parser<T> parser);

**Comment by hudson-s** [comment]
独立app 目前只看见有一个这个接口        MiotManager.getDeviceManager().callSmarthomeApi(path, jsonObject, callback);  现在是否有办法能通过改变json 来支持host前缀形式

**Comment by hanbingwuxie** [comment]
目前独立app使用的是 open auther 接口只能访问特定的API，如果接口不支持，加host前缀也无法访问正常接口的
