### ISSUE TITLE
与[MJFAppConfigOperation shared] getAppconfigWithConfigName 有同样功能的接口是哪个？

### ISSUE THREAD

**Issue by bingerZhang** [MiEcosystem/mijiaSDK#13]
[MJFAppConfigOperation shared] getAppconfigWithConfigName 是在IOS SDK中提供的接口，请问在andorid SDK中哪一个接口与之对应，有同样的功能？

**Comment by M201370367** [comment]
可以用每个设备对应的Service来获取：
类：com.miot.common.device.Service
函数：getProperties()
