### ISSUE TITLE
问题：getRemoteDeviceList列表是有序的吗

### ISSUE THREAD

**Issue by Aphrodite123** [MiEcosystem/mijiaSDK#14]
MiotManager.getDeviceManager().getRemoteDeviceList
这个接口查出来的设备列表是有序的吗？

**Comment by M201370367** [comment]
设备列表从服务器中获取列表返回，米家sdk没有做排序处理。

**Comment by Aphrodite123** [comment]
那么如何判断当前绑定的设备是哪个呢？

**Comment by M201370367** [comment]
返回的设备都是当前已绑定的设备。如果需要上一次绑定的设备，可以在自己代码里本地保存did，下次需要用设备时取出来，通过did去获取设备。
