### ISSUE TITLE
获取设备列表时 binder died

### ISSUE THREAD

**Issue by coderLM** [MiEcosystem/mijiaSDK#38]
系统：Android 9 MIUI10.3.2
SDK版本：
   compile 'com.miot.bluetooth:mijia:3.3.14@aar'
    compile 'com.miot.api:mijia:3.3.14@aar'
    compile 'com.miot.service:mijia:3.3.14@aar'
    compile 'com.xiaomi.account:oauth-android:2.0.9' 

之前所有操作正常（
 MiotManager.getInstance().initialize(getApplicationContext());
 MiotManager.getInstance().setAppConfig(appConfig);
MiotManager.getPeopleManager().savePeople(people);）

当调用MiotManager.getDeviceManager().getRemoteDeviceList(mDeviceHandler);时报错:
![image](https://user-images.githubusercontent.com/46736981/65747201-683e3600-e133-11e9-8bca-afdc764c68ed.png)

![image](https://user-images.githubusercontent.com/46736981/65740769-72086f00-e11c-11e9-990a-566690db3249.png)
![image](https://user-images.githubusercontent.com/46736981/65747251-873cc800-e133-11e9-9621-75fa8196dd4e.png)

日志文件：
[log.txt](https://github.com/MiEcosystem/mijiaSDK/files/3661208/log.txt)

**Comment by M201370367** [comment]
定位因为少添加了okhttp库导致miotService进程挂掉，已解决。
